export const buildings = [
  { id: 'lib', name: 'Library', floors: 5 },
  { id: 'science', name: 'Science Hall', floors: 4 },
  { id: 'tech', name: 'Tech Center', floors: 6 },
  { id: 'arts', name: 'Arts Room', floors: 3 },
  { id: 'student', name: 'Student Center', floors: 4 },
]

export const rooms = [
  {
    id: 'lib-201',
    name: 'Library',
    building: 'Library',
    floor: 2,
    capacity: 8,
    occupancy: 3,
    availability: 'available' as const,
    coordinates: [25.1, 55.2],
  },
  
  {
    id: 'science-102',
    name: 'Science Hall',
    building: 'Science Hall',
    floor: 1,
    capacity: 25,
    occupancy: 15,
    availability: 'busy' as const,
    coordinates: [25.3, 55.1],
  },
  
  {
    id: 'tech-401',
    name: 'Tech Center',
    building: 'Tech Center',
    floor: 4,
    capacity: 40,
    occupancy: 5,
    availability: 'available' as const,
    coordinates: [25.4, 55.4],
  },

  {
    id: 'arts-102',
    name: 'Arts Room',
    building: 'Arts Room',
    floor: 1,
    capacity: 15,
    occupancy: 12,
    availability: 'busy' as const,
    coordinates: [25.5, 55.5],
  },
  {
    id: 'student-301',
    name: 'Student Center',
    building: 'Student Center',
    floor: 3,
    capacity: 30,
    occupancy: 0,
    availability: 'available' as const,
    coordinates: [25.6, 55.6],
  },
]

export const timetable = [
  {
    id: 'class-1',
    code: 'CS101',
    name: 'Introduction to Computer Science',
    instructor: 'Dr. Smith',
    room: 'science-201',
    building: 'Science Hall',
    floor: 2,
    startTime: '09:00',
    endTime: '10:30',
    day: 'Monday',
    enrolled: true,
  },
  {
    id: 'class-2',
    code: 'MATH201',
    name: 'Calculus II',
    instructor: 'Prof. Johnson',
    room: 'science-102',
    building: 'Science Hall',
    floor: 1,
    startTime: '11:00',
    endTime: '12:30',
    day: 'Monday',
    enrolled: true,
  },
  {
    id: 'class-3',
    code: 'ENG102',
    name: 'Literature & Composition',
    instructor: 'Dr. Williams',
    room: 'arts-102',
    building: 'Arts Room',
    floor: 1,
    startTime: '14:00',
    endTime: '15:30',
    day: 'Tuesday',
    enrolled: true,
  },
  {
    id: 'class-4',
    code: 'PHYS301',
    name: 'Modern Physics',
    instructor: 'Prof. Brown',
    room: 'science-201',
    building: 'Science Hall',
    floor: 2,
    startTime: '13:00',
    endTime: '14:30',
    day: 'Wednesday',
    enrolled: true,
  },
]

export const facilities = [
  {
    id: 'cafeteria',
    name: 'Main Cafeteria',
    building: 'Student Center',
    floor: 1,
    type: 'dining',
    hours: '7:00 AM - 10:00 PM',
    coordinates: [25.6, 55.58],
  },
  {
    id: 'gym',
    name: 'Sports Complex',
    building: 'Student Center',
    floor: 2,
    type: 'fitness',
    hours: '6:00 AM - 11:00 PM',
    coordinates: [25.58, 55.62],
  },
  {
    id: 'health',
    name: 'Health Center',
    building: 'Library',
    floor: 1,
    type: 'medical',
    hours: '8:00 AM - 6:00 PM',
    coordinates: [25.1, 55.18],
  },
  {
    id: 'bookstore',
    name: 'Campus Bookstore',
    building: 'Student Center',
    floor: 1,
    type: 'retail',
    hours: '9:00 AM - 8:00 PM',
    coordinates: [25.62, 55.6],
  },
]

export const helpDeskCategories = [
  { id: 'navigation', label: 'Navigation Help', icon: 'MapPin' },
  { id: 'booking', label: 'Room Booking', icon: 'Clock' },
  { id: 'facilities', label: 'Facilities', icon: 'Building2' },
  { id: 'technical', label: 'Technical Support', icon: 'Cpu' },
  { id: 'academic', label: 'Academic Info', icon: 'BookOpen' },
  { id: 'other', label: 'Other', icon: 'HelpCircle' },
]
